version: "3"

services:
  one:
    image: 'h3ar7b3a7/one:latest'
    container_name: 'ONE'
    ports:
      - '8080:8080'
    environment:
      - DESTINATION_CLIENT=192.168.0.251:8081
      - logging.file.name=log/one.log
    volumes:
      - elastic_data:/workspace/log/
    networks:
      - default

  two:
    image: 'h3ar7b3a7/two:latest'
    container_name: 'TWO'
    ports:
      - '8081:8080'
    environment:
      - logging.file.name=log/two.log
    volumes:
      - elastic_data:/workspace/log/
    networks:
      - default

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
      - elastic_data:/usr/share/logstash/data/
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - es
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default

  es:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - default

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://192.168.0.251:9200
    depends_on:
      - es
    networks:
      - default

volumes:
  elastic_data: {}

networks:
  default: